### ISSUE TITLE
Result Cant change from another user key

### ISSUE THREAD

**Issue by jamilalidrus** [bborrel/google-scholar-profile-parser#1]
i was make a test for two account google schoolar key, while i try for the fist account i get well result, but when i am trying using the second account google schoolar key.... the result always show the first people result... what i have to do?

**Comment by jamilalidrus** [comment]
i was check to google schoolar, author has more than 100 resarch, but while i try this package, the result just showing 100 data. how to solve it?

**Comment by bborrel** [comment]
> i was check to google schoolar, author has more than 100 resarch, but while i try this package, the result just showing 100 data. how to solve it?

You should do one request for each scholar id.


> i was make a test for two account google schoolar key, while i try for the fist account i get well result, but when i am trying using the second account google schoolar key.... the result always show the first people result... what i have to do?

Google may implement some limitations in the use of their services in general, and Scholar in particular. Those limitations doesn't apply for humans browsing, but for crawlers/scrappers and may be based on your device's IP, set on a daily basis... I searched in their Terms of Service but didn't find any detailed information.

**Comment by bborrel** [comment]
closing

**Comment by bborrel** [comment]
If you need to scale up, you may be interesting in [paid and free alternatives using proxies](https://www.scraperapi.com/blog/best-google-scholar-apis-proxies/).
