### ISSUE TITLE
getPublicationURL() method issue

### ISSUE THREAD

**Issue by martinGHub** [bborrel/google-scholar-profile-parser#3]
Hello over there,

I'm getting just https://scholar.google.com in any returns of the _getPublicationURL()_ method. Here some output of the example-publications.php in https://github.com/bborrel/google-scholar-profile-parser/blob/master/doc/example-publications.php:

_[...]_
_2018
On the oblique impact dynamics of drops on superhydrophobic surfaces. Part II: Restitution coefficient and contact time
**https://scholar.google.com**
DGK Aboud, AM Kietzig
Langmuir 34 (34), 9889-9896
18
https://scholar.google.com/scholar?oi=bibs&hl=en&oe=ASCII&cites=16533606600830692394
2018
Colored poly (vinyl chloride) by femtosecond laser machining
**https://scholar.google.com**
KMT Ahmmed, R Mafi, AM Kietzig
Industrial & Engineering Chemistry Research 57 (18), 6161-6170
4
https://scholar.google.com/scholar?oi=bibs&hl=en&oe=ASCII&cites=9620504647520746039
2018
Wettability modification of porous PET by atmospheric femtosecond PLD
**https://scholar.google.com**
Y Assaf, G Forstmann, AM Kietzig
Applied Surface Science 436, 1075-1082
4
https://scholar.google.com/scholar?oi=bibs&hl=en&oe=ASCII&cites=11462441141976584651
2018
Optical and chemical effects governing femtosecond laser-induced structure formation on polymer surfaces
**https://scholar.google.com**
Y Assaf, AM Kietzig
Materials Today Communications 14, 169-179
16
https://scholar.google.com/scholar?oi=bibs&hl=en&oe=ASCII&cites=17266659071435387270
2018
Effect of Particle Loading and Stability on the Wetting Behavior of Nanofluids
**https://scholar.google.com**
A Karthikeyan, S Coulombe, AM Kietzig
Advances in Contact Angle, Wettability and Adhesion, Volume 3 3, 179_

***
Before, I was getting a full publication URL with useful information, but now, as you seen in bold, are just the Google Scholar domain.

I'm using PHP 7.2.24 (CLI). Below, pasted all the _php -version_ output:

_PHP 7.2.24-0ubuntu0.18.04.6 (cli) (built: May 26 2020 13:09:11) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.18.04.6, Copyright (c) 1999-2018, by Zend Technologies_

Thank you in advance.

**Comment by bborrel** [comment]
Hi @martinGHub, find the fix in the branch of the PR #4. Please confirm it fixes the issue here. I will then create a new 2.x release.

**Comment by bborrel** [comment]
Hi @martinGHub, find the fix in the branch of the PR #4. Please confirm it fixes the issue here. I will then create a new 2.x release.

**Comment by martinGHub** [comment]
Hello @bborrel. Great! it's working now. Thank you very much for your help.

**Comment by bborrel** [comment]
fixed by PR #4
